
-- Create a table for contact submissions
create table contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  business_type text,
  project_details text
);

-- Reset Row Level Security to be open for this demo (or configure as needed)
alter table contact_submissions enable row level security;

-- Create policy to allow open access for inserts (anyone can submit)
create policy "Enable insert for all users"
on "public"."contact_submissions"
as PERMISSIVE
for INSERT
to public
with check (true);

-- Create policy to allow read access only to authenticated users (admins) or just leave it closed for public
create policy "Enable read access for authenticated users only"
on "public"."contact_submissions"
as PERMISSIVE
for SELECT
to authenticated
using (true);
